# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y9Qn7Mppmzuq3gOaCqx7GILmBwEOedPh
"""

n = 7
print(n*n)